=== FreeAndFair/setup-texlive-action/packages/data/schemas/tlnet.schema.json
{
  "$id": "tlnet.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "ctan": {
      "$ref": "#/$defs/tlnet"
    },
    "tlcontrib": {
      "$ref": "#/$defs/tlnet"
    },
    "historic": {
      "$ref": "#/$defs/tlnet"
    },
    "tlpretest": {
      "$ref": "#/$defs/tlnet"
    }
  },
  "required": ["ctan", "tlcontrib", "historic", "tlpretest"],
  "patternProperties": {
    "^\\$.*$": {}
  },
  "additionalProperties": false,
  "$defs": {
    "tlnet": {
      "type": "object",
      "properties": {
        "master": {
          "description": "Master repository URL",
          "type": "string",
          "format": "uri"
        },
        "mirrors": {
          "description": "Mirror multiplexor URL",
          "type": "string",
          "format": "uri"
        },
        "default": {
          "description": "Mirror URL used by default",
          "type": "string",
          "format": "uri"
        },
        "path": {
          "description": "tlnet path",
          "oneOf": [
            {
              "type": "string",
              "format": "uri-template"
            },
            {
              "type": "object",
              "propertyNames": {
                "format": "uri-template"
              },
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "versions": {
                    "$ref": "#/$defs/semverRange"
                  }
                },
                "required": ["versions"],
                "additionalProperties": false
              }
            }
          ]
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "semverRange": {
      "type": "string"
    }
  }
}

=== FreeAndFair/setup-texlive-action/packages/data/data/tlnet.json
{
  "$schema": "../schemas/tlnet.schema.json",
  "ctan": {
    "master": "http://dante.ctan.org/tex-archive/",
    "mirrors": "https://mirrors.ctan.org/",
    "default": "https://mirror.math.princeton.edu/pub/CTAN/",
    "path": "systems/texlive/tlnet/"
  },
  "tlcontrib": {
    "mirrors": "https://mirrors.ctan.org/",
    "path": "systems/texlive/tlcontrib/"
  },
  "historic": {
    "master": "ftp://tug.org/historic/",
    "default": "https://ftp.math.utah.edu/pub/texlive/historic/",
    "path": {
      "systems/texlive/{version}/tlnet/": {
        "versions": "<2010"
      },
      "systems/texlive/{version}/tlnet-final/": {
        "versions": ">=2010"
      }
    }
  },
  "tlpretest": {
    "default": "https://ftp.math.utah.edu/pub/texlive/tlpretest/"
  }
}
